[[d1_databases]]
binding = "propiedadesyparcelas_db"
database_name = "propiedadesyparcelas-db"
database_id = "ac88ce1c-c842-400b-b167-8c48c9608f9e"

[[r2_buckets]]
binding = "BUCKET_FOTOS"
bucket_name = "propiedadesyparcelas-fotos"
