name = "propiedadesyparcelas"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

# Activar logs para diagnosticar errores en producción
[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "propiedadesyparcelas-db"
database_id = "ac88ce1c-c842-400b-b167-8c48c9608f9e"

[[r2_buckets]]
binding = "BUCKET_FOTOS"
bucket_name = "propiedadesyparcelas-fotos"
